### ISSUE TITLE
not all ressources are shown

### ISSUE THREAD

**Issue by tbleiker** [ThePromidius/tachiyomi-extensions#26]
### Source information

Kavita v1.3.5

### Steps to reproduce

1. setup Kavita extension (set OPDS url, restart app etc.)
2. browse to Kavita content (browse --> sources --> Kavita)

### Expected behavior

all resources (ebooks, comics etc.) are shown

### Actual behavior

not all resources are shown

### Tachiyomi version

stable v0.13.5

### Android version

Android 11

### Other details

- currently 3 libraries on Kavita
- each contains only a couple of resources
- content of one library is not shown at all in Tachiyomi
- only half of the content of the other libraries are shown
- however, resources are shown when searched for

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ThePromidius** [comment]
Pdfs and ebooks are not supported. Only Comics and Manga.
Does this solve the issue?

**Comment by tbleiker** [comment]
oh, how unfortunate... I wasn't aware of that. But yes, that solves the issue. Thx (and thx for your fast response!)
