### ISSUE TITLE
Kavita plugin not working.

### ISSUE THREAD

**Issue by Govik** [ThePromidius/tachiyomi-extensions#27]
### Source information

Kavita 1.3.5

### Steps to reproduce

Configure kavita plugin with OPDS URL and restart tachiyomi and try to browse kavita.

### Expected behavior

Should load my kavita library.

### Actual behavior

Error window showing "No resulsts found"

### Tachiyomi version

0.13.5

### Android version

Android 9.0

### Other details

I am unable to get OPDS working in the Tachiyomi app via kavita extension. I have tried with reverse proxy and local IP address. OPDS is enabled. I can browse to Kavita via my subdomain and local IP just fine. When I use the OPDS URL in my browser I get an XML file which I have read is normal behavior. Not sure of any other app to try to see if it might be an issue with the Tachiyomi extension. Would be happy to send any info needed or try any suggestions and would appreciate any help. I have tried on my phone and tablet. With my phone I have tried via my wifi for lan and data plan to get connection over internet instead of lan.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Govik** [comment]
fixed it

**Comment by koinupapi** [comment]
@Govik how did you fix it? I'm facing a similar issue where it says that the address is incorrect, even though I've copied it directly from kavita, and it does the same, it shows the xml feed when viewing directly. 

Tachiyomi even offers a button for me to use the webview, and it takes me to the home page just fine.
