### ISSUE TITLE
kavita

### ISSUE THREAD

**Issue by trngkn** [ThePromidius/tachiyomi-extensions#31]
### Source information and language

Kavita - English

### Steps to reproduce

1. install extension
2. go to my source and enter my ODPS link
3. cant see anything

### Expected behavior

Show all my ebooks

### Actual behavior

cant found any result

### Tachiyomi version

0.14.5

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ThePromidius** [comment]
Tachiyomi extension only supports Manga and comics (cbx files) and pdfs. 
It does not support ebooks yet and thus why you can't filter those.
